# This is a basic workflow to help you get started with Actions

name: for my girl daily morning

# Controls when the workflow will run
on:
  schedule:
  - cron:  '0 7 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send_message:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: send morning to my girl
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      START_DATE: ${{ secrets.START_DATE }}
      CITY: ${{ secrets.CITY }}
